/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadejemplo.Vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author francisco
 */
public class InscripcionInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form InscripcionInternalFrame
     */
    public InscripcionInternalFrame() {
        initComponents();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jBManipulaNota = new javax.swing.JButton();
        jBManejaInscrip = new javax.swing.JButton();

        setClosable(true);
        setTitle("Formulario de Inscripcion");

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("ELEGIR LA OPCION DESEADA:");

        jBManipulaNota.setText("Manipulacion de notas");
        jBManipulaNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBManipulaNotaActionPerformed(evt);
            }
        });

        jBManejaInscrip.setText("Manejo de inscripcion");
        jBManejaInscrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBManejaInscripActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jBManipulaNota, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jBManejaInscrip, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jBManipulaNota)
                        .addGap(107, 107, 107)
                        .addComponent(jBManejaInscrip))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel1)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jBManipulaNota))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jBManejaInscrip)))
                .addContainerGap(449, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBManipulaNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBManipulaNotaActionPerformed
        // TODO add your handling code here:
        ManejoNotas uno = new ManejoNotas();
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        
        uno.setVisible(true);
        jDesktopPane1.add(uno);
        jDesktopPane1.moveToFront(uno);
    }//GEN-LAST:event_jBManipulaNotaActionPerformed

    private void jBManejaInscripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBManejaInscripActionPerformed
        // TODO add your handling code here:
        ManipulacionInscripcion uno = new ManipulacionInscripcion();
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        uno.setVisible(true);
        jDesktopPane1.add(uno);
        jDesktopPane1.moveToFront(uno);
    }//GEN-LAST:event_jBManejaInscripActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBManejaInscrip;
    private javax.swing.JButton jBManipulaNota;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativoTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
